### ISSUE TITLE
Add custom fields to settings tab

### ISSUE THREAD

**Issue by timdreier** [zeroseven/pagebased#2]
Hi,
thanks for this great extension!

I'm currently trying to migrate from z7_blog to page based. How can I add additional / custom fields to an object?

**Comment by raphaelthanner** [comment]
Hi @timdreier,

you can extend the extbase model and page properties in the "normal TYPO3 way".

To display the field only on a specific pagebased type you can create a display condition using the `TCAUtility`.

Here is an example:

**my_extension/Configuration/TCA/Overrides/pages.php**

```php
// Add field to all page types
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('pages', 'my_new_field', '', 'after:pagebased_contact');

// Add custom display condition
$registration = \Zeroseven\Pagebased\Registration\RegistrationService::getRegistrationByIdentifier('my_extension');
\Zeroseven\Pagebased\Utility\TCAUtility::addObjectDisplayCondition($registration, 'my_new_field');
```

We hope you continue to have fun with this extension!
But first and foremost, Merry Christmas :santa:
